---
title: "Project Outline"
output: html_document
---

```{r}
require(tidyverse)
require(jsonlite)
require(httr)
require(devtools)
require(jsonlite)
require(dplyr)
require(readr)
library(shiny)
library(shinyjs)
library(leaflet)
library(maps)


ny <- read_csv("data/meetup_groupsNYlocation.csv",  col_names = FALSE)
bo <- read_csv("data/MA.csv", col_names= FALSE)
ch <- read_csv("data/NC.csv", col_names=FALSE)
ha <- read_csv("data/CT.csv", col_names=FALSE)

#Function to rename columns for each dataset
column_rename <- function(x) {
colnames(x)[1] <- "city"
colnames(x)[2] <- "group_name"
colnames(x)[3] <- "created"
colnames(x)[4] <- "category"
colnames(x)[5] <- "members"
colnames(x)[6] <- "details"
colnames(x)[7] <- "lat"
colnames(x)[8] <- "long"
}

column_rename(x = ny)
column_rename(x = bo)
column_rename(x = ch)
column_rename(x = ha)

#top categories based on members
top10 <- function(data) {
  data %>%
    group_by(category) %>%
    summarize(members_tot = sum(members))  %>%
    arrange(desc(members_tot)) %>%
    head(10)
}

 chtop10<-top10(data=ch)
 hatop10<-top10(data=ha)
botop10<-top10(data=bo)
nytop10<-top10(data=ny) 

ggplot(data=chtop10, aes(x=category, y=members_tot))+geom_bar(stat="identity") + labs(title = "Charlotte top categories by membership") 
ggplot(data=botop10, aes(x=category, y=members_tot))+geom_bar(stat="identity") + labs(title = "Boston top categories by membership") 
ggplot(data=hatop10, aes(x=category, y=members_tot))+geom_bar(stat="identity") + labs(title = "Hartford top categories by membership") 
ggplot(data=nytop10, aes(x=category, y=members_tot))+geom_bar(stat="identity") + labs(title = "New York top categories by membership") 
#Renaming columns and cleaning up 
Boston_MA<-bo[c(2, 4:7, 9:10, 13:15)]
Charlotte_NC<-ch[c(2, 4:7, 9:10, 13:15)]
Hartford_CT<-ha[c(2, 4:7, 9:10, 13:15)]




```


```{r}
#creates df topics with number of groups per topic (fix this)
mostgroups<- function(data){
  topics <-data %>% 
  group_by(category) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count));topics
}

mostgroups(ch)
mostgroups(ny)
mostgroups(bo)
View(bo)
topics <- ny %>% 
  select(category, members) %>% 
  group_by(category) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count));topics
View(ny)

topics10 <- topics %>% 
  head(10)
  
#graph of densities of topics
ggplot( data = topics, aes(x = count)) + geom_density(adjust = 0.29) + labs(title = "") 

#graph of number of members in top 10 topics (stacked bargraph)

```

```{r}
colnames(ny)[1] <- "city"
colnames(ny)[2] <- "group_name"
colnames(ny)[3] <- "created"
colnames(ny)[4] <- "category"
colnames(ny)[5] <- "members"
colnames(ny)[6] <- "details"
colnames(ny)[7] <- "lat"
colnames(ny)[8] <- "long"

nysocializing <- ny %>% 
  filter(category == "socializing")

nylanguage <- ny %>% 
  filter(category == "language/ethnic identity")

nytech <- ny %>% 
  filter(category == "tech")

nysports <- ny %>% 
  filter(category == "sports/recreation")
```

```{r}
#Hartford
colnames(ha)[1] <- "city"
colnames(ha)[2] <- "group_name"
colnames(ha)[3] <- "created"
colnames(ha)[4] <- "category"
colnames(ha)[5] <- "members"
colnames(ha)[6] <- "details"
colnames(ha)[7] <- "lat"
colnames(ha)[8] <- "long"

ctsocializing <- ha %>% 
  filter(category == "socializing")

ctlanguage <- ha %>% 
  filter(category == "language/ethnic identity")

cttech <- ha %>% 
  filter(category == "tech")

ctsports <- ha %>% 
  filter(category == "sports/recreation")
```

```{r}
#Boston
colnames(bo)[1] <- "city"
colnames(bo)[2] <- "group_name"
colnames(bo)[3] <- "created"
colnames(bo)[4] <- "category"
colnames(bo)[5] <- "members"
colnames(bo)[6] <- "details"
colnames(bo)[7] <- "lat"
colnames(bo)[8] <- "long"

bosocializing <- bo %>% 
  filter(category == "socializing")

bolanguage <- bo %>% 
  filter(category == "language/ethnic identity")

botech <- bo %>% 
  filter(category == "tech")

bosports <- bo %>% 
  filter(category == "sports/recreation")
```

```{r}
#Charlotte
colnames(ch)[1] <- "city"
colnames(ch)[2] <- "group_name"
colnames(ch)[3] <- "created"
colnames(ch)[4] <- "category"
colnames(ch)[5] <- "members"
colnames(ch)[6] <- "details"
colnames(ch)[7] <- "lat"
colnames(ch)[8] <- "long"

chsocializing <- ch %>% 
  filter(category == "socializing")

chlanguage <- ch %>% 
  filter(category == "language/ethnic identity")

chtech <- ch %>% 
  filter(category == "tech")

chsports <- ch %>% 
  filter(category == "sports/recreation")
```


As you can see, the category with the most groups is "socializing". Given how at it's core meetup is designed to bring people together over shared interests, it is no wonder that socializing has the highest volume of meetup groups. The majority of topics (approxiamately 30%) have between 5 and 25 dedicated groups.


```{r}
smallCT <- Hartford_CT %>% 
  select(category, lat, lon, yes_rsvp_count)
smallCT <- na.omit(smallCT)
```

```{r}
smallMA <- Boston_MA %>% 
  select(category, lat, lon, yes_rsvp_count)
smallMA <- na.omit(smallMA)
```

```{r}
smallNC <- Charlotte_NC %>% 
  select(category, lat, lon)
smallNC <- na.omit(smallNC)
```

#Shiny Time

```{r}
#Template
Aukland <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
Aukland  # Print the map
```

```{r}
#Icons
greenIcon <- makeIcon(
  iconUrl = "https://cdn.rawgit.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-green.png",
  iconWidth = 25, iconHeight = 41,
  iconAnchorX = 12, iconAnchorY = 41
)

redIcon <- makeIcon(
  iconUrl = "https://cdn.rawgit.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-red.png",
  iconWidth = 25, iconHeight = 41,
  iconAnchorX = 12, iconAnchorY = 41
)

orangeIcon <- makeIcon(
  iconUrl = "https://cdn.rawgit.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-orange.png",
  iconWidth = 25, iconHeight = 41,
  iconAnchorX = 12, iconAnchorY = 41
)
```


```{r}
# map of NY with events as category

NY  <- leaflet() %>%
  addTiles() %>%  
  #markers(Hartford)# Add default OpenStreetMap map tiles
  addMarkers(data=nysocializing, popup="social",icon=orangeIcon) %>% 
  addMarkers(data=nylanguage, popup="language",icon=greenIcon) %>% 
  addMarkers(data=nysports, popup="sports",icon=redIcon) %>% 
  addMarkers(data=nytech, popup="tech")
NY
```

```{r}
# map of Hartford
hartfordmap  <- leaflet() %>%
  addTiles() %>%  
  #markers(Hartford)# Add default OpenStreetMap map tiles
  addMarkers(data=ctsocializing, popup="social",icon=orangeIcon) %>% 
  addMarkers(data=ctlanguage, popup="language",icon=greenIcon) %>% 
  addMarkers(data=ctsports, popup="sports",icon=redIcon) %>% 
  addMarkers(data=cttech, popup="tech")
hartfordmap
```

```{r}
# map of Boston
bostonmap  <- leaflet() %>%
  addTiles() %>%  
  #markers(Hartford)# Add default OpenStreetMap map tiles
  addMarkers(data=bosocializing, popup="social",icon=orangeIcon) %>% 
  addMarkers(data=bolanguage, popup="language",icon=greenIcon) %>% 
  addMarkers(data=bosports, popup="sports",icon=redIcon)%>% 
  addMarkers(data=botech, popup="tech")
bostonmap
```

```{r}
# map of Charlotte
charlottemap  <- leaflet() %>%
  addTiles() %>%  
  #markers(Hartford)# Add default OpenStreetMap map tiles
  addMarkers(data=chsocializing, popup="social",icon=orangeIcon) %>% 
  addMarkers(data=chlanguage, popup="language",icon=greenIcon) %>% 
  addMarkers(data=chsports, popup="sports",icon=redIcon) %>% 
  addMarkers(data=chtech, popup="tech")
charlottemap
```
